title: Stackbit Fjord Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: yellow
header:
  title: Fjord
  tagline: The practical guide for the casual rewards traveler
  logo_img: images/Png logo color.png
  logo_img_alt: Fjord Logo
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: About
      url: /about
      style: link
    - label: Blog
      url: /style-guide
      style: link
    - label: Contact
      url: /contact
      style: link
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: icon
      icon_class: twitter
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/'
      style: icon
      icon_class: instagram
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      style: icon
      icon_class: github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: linkedin
      new_window: true
    - label: DEV
      url: 'https://dev.to/'
      style: icon
      icon_class: dev
      new_window: true
  background_img: images/Main Banner websitejpg.jpg
footer:
  content: ''
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
